logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: gateway
  cloud:
    gateway:
     # default-filters:
      #   - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      #   globalcors:
      #    corsConfigurations:
      #     '[/**]':
      #      allowedOrigins: "http://localhost:4200"
      #      allowedMethods: "*"
      #      allowedHeaders: "*"
      routes:
        - id: userModule
          uri: http://localhost:8098/
          predicates:
            - Path=/api/**
        - id: associationModule
          uri: http://localhost:8081/
          predicates:
            - Path=/Association/**,/Reclamation/**,/swagger-ui/**
        - id: baladeModule
          uri: http://localhost:8096/
          predicates:
            - Path=/balade/**
        - id: programmeModule
          uri: http://localhost:8099/
          predicates:
            - Path=/prog/**
        - id: eventModule
          uri: http://localhost:8088/
          predicates:
            - Path=/event/**,/comment/**
        - id: maintenanceModule
          uri: http://localhost:3000/
          predicates:
            - Path=/velo/**
        - id: veloModule
          uri: http://localhost:3001/
          predicates:
            - Path=/maintenance/**
        - id: velorentModule
          uri: http://localhost:8090/
          predicates:
            - Path=/velorent/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/gateway-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
