version: "3"
services:
    springboot-app:
        container_name: association-reclamation-micro-service
        image: repo/micro-service
        restart: always
        build: .
        ports:
            - "8081:8081"
        environment:
            MYSQL_HOST: mysqldb
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_PORT: 3306

    eureka-server:
        build:
            context:

        image: repo/eureka-server

        hostname: eureka-server
        ports:
            - "8761:8761"
        links:
            - springboot-app
    mysqldb:
        container_name: mysqldb
        image: mysql
        ports:
            - 3307:3306
        environment:
            MYSQL_DATABASE: Velo
            MYSQL_ROOT_PASSWORD: root
